name: C/C++ CI

on:
  push:
    branches: [ "heaviside_activation_function" ]
  pull_request:
    branches: [ "heaviside_activation_function" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make standart activate function
      run: make 
    - name: run standart activate function
      run: ./main
    # - name: make heaviside activate function
    #   run: make heaviside
    # - name: run heaviside activate function
    #   run: ./main
